set(idlmm_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/IdlmmFactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/IdlmmFactoryImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ModelElement.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Contained.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/InterfaceDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ModuleDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/IDLType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/OperationDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/AttributeDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ConstantDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Typed.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ParameterDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/PrimitiveDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ExceptionDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Field.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/FixedDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/WstringDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/StringDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/AliasDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ArrayDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/SequenceDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnionField.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/TypedefDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnionDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/EnumDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/StructDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/TranslationUnit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Include.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Expression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/BinaryExpression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnaryExpression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/LiteralExpression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ConstantDefRef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ValueExpression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ForwardDef.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/EnumMember.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Constant.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/NamedElement.cpp
   )

set(idlmm_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm_forward.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/IdlmmFactory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ModelElement.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Container.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Contained.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/InterfaceDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ModuleDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/IDLType.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/OperationDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/AttributeDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ConstantDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Typed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ParameterDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/PrimitiveDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ExceptionDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Field.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/FixedDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/WstringDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/StringDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/AliasDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ArrayDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/SequenceDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnionField.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/TypedefDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnionDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/EnumDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/StructDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/TranslationUnit.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Include.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Expression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/BinaryExpression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/UnaryExpression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/LiteralExpression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ConstantDefRef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ValueExpression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/ForwardDef.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/EnumMember.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/Constant.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/idlmm/NamedElement.hpp
   )

add_library(idlmm SHARED ${idlmm_HEADERS} ${idlmm_SOURCES})
#set_target_properties(idlmm PROPERTIES VERSION 0.0.1 SOVERSION 1)

install(TARGETS idlmm DESTINATION lib)

